language: python
sudo: required
python:
  - "3.5"
  - "3.6"
  # - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
# command to install dependencies
# install: "pip install -r requirements.txt"

install:
  - sudo apt update
  - sudo apt install -y iputils-ping
  - pip3 install -U pytest
  - pip3 install -e .
# command to run tests
script:
  - python3 -m pytest test
